dist: 
- focal
- bionic
- xenial
os: 
- linux
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
install:
- python setup.py develop
- pip install nose mock
- pip install pandas
script: python runtest.py
notifications:
    email: true
    on_success: change
    on_failure: always
