name: rtdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - typing-extensions>=4.9.0
  - numpy
  - scipy
  - numba
  - python-dateutil
  - pandas
  - pre-commit
  - black
  - flake8
  - pytest>=7.0.0
  - coverage
  - pyarrow>=4.0.0