name: rtdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - numba
  - python-dateutil
  - pandas
  - pre-commit
  - black
  - flake8
  - pytest
  - coverage
  - pyarrow>=4.0.0