package:
  name: riptable
  version: "{{ environ.get('BUILD_VERSION', 'DEV') }}"

build:
  number: 0
  noarch: python
  # Use Python installed in host environment.
  script: "{{ PYTHON }} -m pip install -v --no-deps --ignore-installed ."

source:
  - path: ../

requirements:
  host:
    - python {{ python}}
    - setuptools_scm
  run:
    - python
    - ansi2html >=1.5.2
    - numpy >=1.23
    - numba >=0.56.2
    - pandas >=1.0,<3.0
    - python-dateutil
    - riptide_cpp >=1.16.0,<2 # run with any (compatible) version in this range

about:
  home: https://github.com/rtosholdings/riptable
  license: BSD 3-Clause+Patent License
  license_file:
    - LICENSE
    - LICENSES-thirdparty.md
  summary: "Python Package for riptable studies framework"
