package:
  name: riptable
  version: "{{ environ.get('BUILD_VERSION', 'DEV') }}"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  - path: ../

requirements:
  host:
    - python {{ python}}
    - setuptools_scm
  run:
    - python
    - riptide_cpp >=1.8,<2  # run with any (compatible) version in this range
    - pandas >=0.24,<2.0
    - ansi2html >=1.5.2
    - numpy >=1.21
    - numba >=0.55.2
    - python-dateutil

test:
  source_files:
    - riptable
  requires:
    - pytest >=5.0.0
    - pytest-cov >=2.7.1
    - pytest-xdist >=1.32
    - hypothesis >=5.10.0
    - ipython >=7.6.1
    - nose >=1.3.7  # nose because ipykernel testing utilities still have nose imports
    # Include pyarrow as a test requirement. It's an optional dependency at run-time,
    # but we want to be able to run interop tests with it.
    - pyarrow >=6.0.0
    # Include bokeh as a test requirement, as it's an optional run-time dependency.
    - bokeh
    # Known issues where ipykernel dies before reply messages.
    # The following ipykernel and jupyter_console versions are verified to work.
    # https://github.com/jupyter/jupyter_client/issues/154
    - ipykernel >=5.1.3
    - jupyter_console >=6.0.0
  imports:
    - riptable
  commands:
    # Assumes RECIPE_DIR={root}/conda_recipe, to output report into {root}/test-output.
    - pytest -v riptable/tests --junitxml {{RECIPE_DIR}}/../test-output/report.xml

about:
  home: https://github.com/rtosholdings/riptable
  license: BSD 3-Clause+Patent License
  license_file:
    - LICENSE
    - LICENSES-thirdparty.md
  summary: "Python Package for riptable studies framework"
