package:
  name: riptable
  version: "{{ environ.get('BUILD_VERSION', 'DEV') }}"

build:
  number: 0

source:
  - path: ../

requirements:
  build:
    - python {{ python }}
    # The following requirements are in the build because setup.py requires them.
    - setuptools_scm
    - riptide_cpp >=1.7,<1.8
    - ansi2html >=1.5.2
    - numba >=0.51
    - python-dateutil
  run:
    - python
    - {{ pin_compatible('riptide_cpp', min_pin='x.x', max_pin='x.x') }}
    - pandas >=0.24,<2.0
    - ansi2html >=1.5.2
    - numba >=0.51
    - python-dateutil

test:
  source_files:
    - riptable
  requires:
    - pytest >=5.0.0
    - pytest-cov >=2.7.1
    - pytest-xdist >=1.32
    - hypothesis >=5.10.0
    - ipython >=7.6.1
    - nose >=1.3.7  # nose because ipykernel testing utilities still have nose imports
    # Include pyarrow as a test requirement. It's an optional dependency at run-time,
    # but we want to be able to run interop tests with it.
    - pyarrow >=4.0.0

    # Known issues where ipykernel dies before reply messages.
    # The following ipykernel and jupyter_console versions are verified to work.
    # https://github.com/jupyter/jupyter_client/issues/154
    - ipykernel >=5.1.3
    - jupyter_console >=6.0.0
  imports:
    - riptable

about:
  home: https://github.com/rtosholdings/riptable
  license: BSD 3-Clause+Patent License
  license_file:
    - LICENSE
    - LICENSES-thirdparty.md
  summary: "Python Package for riptable studies framework"
