channels:
  - rtosholdings
  - conda-forge
  - defaults

  # *** IMPORTANT ***
  # Any changes made here must be reflected in gen_requirements.py for build use!
dependencies:
  - ansi2html>=1.5.2
  - arrow
  - ipykernel
  - ipython
  - matplotlib
  - nbsphinx
  - numba>=0.56.2
  - pandas>=1.0,<3.0
  - pip
  - pyarrow
  - pytest
  - python-dateutil
  - riptide_cpp
  - sphinx>=7,<8
  - sphinx_rtd_theme>=0.5.1
  - sphinx-autoapi>=3,<4
  - sphinx-design
  - tomli
